name: linting, testing, building
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build:prod
      - run: npm run lint:ts
        if: always()
      - run: npm run lint:scss
        if: always()
      - run: npm run test:unit
        if: always()
      - run: npm run storybook-build
        if: always()
      - run: npm run test:ui:ci

